# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

tasks:
  - init: |
      for i in $(seq 1 10); do
        sudo sh -c 'echo "0.0.0.0 app$i.zelthy.com" >> /etc/hosts'
      done
  - name: Initalize
    command: |
      pip install locust
      git clone https://github.com/Healthlane-Technologies/zelthy3.git
      cd zelthy3
      git checkout feat/loadtest
      chmod +x loadtest.bash

ports:
  - port: 8080
    visibility: public
